//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabaseScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resources.DatabaseScript", typeof(DatabaseScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- MySQL Workbench Forward Engineering
        ///
        ///SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
        ///SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
        ///SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=&apos;TRADITIONAL,ALLOW_INVALID_DATES&apos;;
        ///
        ///-- -----------------------------------------------------
        ///-- Schema mydb
        ///-- -----------------------------------------------------
        ///-- -----------------------------------------------------
        ///-- Schema school
        ///-- --------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string databasescriptTest {
            get {
                return ResourceManager.GetString("databasescriptTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- MySQL Workbench Forward Engineering
        ///
        ///SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
        ///SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
        ///SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=&apos;TRADITIONAL,ALLOW_INVALID_DATES&apos;;
        ///
        ///-- -----------------------------------------------------
        ///-- Schema mydb
        ///-- -----------------------------------------------------
        ///-- -----------------------------------------------------
        ///-- Schema school
        ///-- --------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string databasscript {
            get {
                return ResourceManager.GetString("databasscript", resourceCulture);
            }
        }
    }
}
